[tool.poetry]
name = "my_app"
version = "0.2.0"
description = "This is a boilerplate application with Flask and SQLAlchemy"
authors = ["CoffeeAnon <dan@danjacobsen.com>"]
readme = "README.md"

[tool.poetry.extras]
test = [
    "pytest",
    "pylint",
    "mypy",
    "types-SQLAlchemy",
    "coverage",
    "types-requests",
    "types-flask-migrate",
    "types-toml",
]


[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3.2"
flask-sqlalchemy = "^3.0.5"
python-dotenv = "^1.0.0"

pytest = { version = "^7.3.1", optional = true }
pylint = { version = "^2.17", optional = true }
coverage = { version = "^7.2.5", optional = true }
types-requests = { version = "^2.28.11", optional = true }
types-SQLAlchemy = { version = "^1.4.53", optional = true }
mypy = { version = "^1.3", optional = true }
flask-migrate = "^4.0.4"
types-flask-migrate = { version = "^4.0.0.6", optional = true }
gunicorn = "^21.2.0"
flask-restx = "^1.1.0"
psycopg2-binary = "^2.9.7"
toml = "^0.10.2"
types-toml = { version = "^0.10.8.7", optional = true }


[tool.poetry.group.dev.dependencies]
debugpy = "^1.6.7.post1"
flake8 = "^6.1.0"
black = "^23.7.0"
pytest = "^7.4.0"
mypy = "^1.5.1"
coverage = "^7.3.0"
pylint = "^2.17.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
