[tool.poetry]
name = "my_app"
version = "0.2.4"
description = "This is a boilerplate application with Flask and SQLAlchemy"
authors = ["CoffeeAnon <dan@danjacobsen.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3"
flask-sqlalchemy = "^3.0"
python-dotenv = "^1.0"
flask-migrate = "^4.0"
gunicorn = "^21.2"
flask-restx = "^1.1"
psycopg2-binary = "^2.9"
toml = "^0.10"

[tool.poetry.group.test.dependencies]
pytest = "^7.4"
pylint = "^2.17"
mypy = "^1.3"
types-SQLAlchemy = "^1.4"
coverage = "^7.3"
types-requests = "^2.28"
types-flask-migrate = "^4.0"
types-toml = "^0.10"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.6"
flake8 = "^6.1"
black = "^23.7"
pytest = "^7.4"
mypy = "^1.5"
pylint = "^2.17"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
