apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-python-flask-boilerplate-prod
  namespace: istio-system
spec:
  issuerRef:
    name: ci-istio-letsencrypt-cloudflare-prod
    kind: ClusterIssuer
    group: cert-manager.io
  secretName: cert-secret-python-flask-boilerplate-prod
  dnsNames:
    - "$HOST"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
# use envsubst to replace with actual values:
# $ export $(cat .env | xargs) && envsubst < manifests/02_cert_prod.yaml | kubectl apply -f -
