"""empty message

Revision ID: cab09b995e1a
Revises: 
Create Date: 2023-09-27 16:45:06.359038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cab09b995e1a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "worlds",
        sa.Column("world_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("world_id"),
    )
    # ### end Alembic commands ###
    conn = op.get_bind()
    insert_stmt = sa.text(
        "INSERT INTO worlds (world_id, name) VALUES ('home', 'Earth');"
    )
    conn.execute(insert_stmt)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("DELETE FROM worlds WHERE world_id = 'home';")

    op.drop_table("worlds")
    op.drop_table("messages")
    # ### end Alembic commands ###
