site_name: Python Flask Boilerplate
repo_url: https://github.com/CoffeeAnon/python_flask_boilerplate
theme:
  name: material

extra:
  version:
    provider: mike

plugins:
  - mike:
      version_selector: true
